{{- if .Values.persistence.dataDir.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "foundry-vtt.fullname" . }}
  labels:
    app: {{ template "foundry-vtt.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
  {{- if not (eq .Values.persistence.storageClass "-") }}
    volume.beta.kubernetes.io/storage-class: {{ default "default" .Values.persistence.storageClass | quote }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: foundry-data
  volumeMode: Filesystem
  selector:
    matchLabels:
      volume: foundry-data
  resources:
    requests:
      storage: {{ .Values.persistence.dataDir.size | quote }}
{{- end -}}
